name: CI

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build_welearn-bg:
    runs-on: ubuntu-18.04
    # runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'welearn-bg' }}
      run: |
        cd ./WeLearn/HerokuContainer
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME