// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeLearn.Data;

namespace WeLearn.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210504173232_FluentAPIRuleRemoved")]
    partial class FluentAPIRuleRemoved
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WeLearn.Data.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("WeLearn.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b0bc5f7e-aab2-47df-b89b-f6ecfa4d2626",
                            Email = "default@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DEFAULT@GMAIL.COM",
                            NormalizedUserName = "USERNAME",
                            PasswordHash = "AQAAAAEAACcQAAAAELvBQ0wJw5Vy2RLZcsC+Lkv4VcOgN5iDTekbET1AQjZL77Yln/SKyPgxQvNVSEXeuw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2a594a73-47ee-41b1-9462-422cfaeed6d3",
                            TwoFactorEnabled = false,
                            UserName = "Username"
                        });
                });

            modelBuilder.Entity("WeLearn.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(273),
                            IsDeleted = false,
                            Name = "Bulgarian Language"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1161),
                            IsDeleted = false,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1165),
                            IsDeleted = false,
                            Name = "Informatics"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1167),
                            IsDeleted = false,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1169),
                            IsDeleted = false,
                            Name = "Geography"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1170),
                            IsDeleted = false,
                            Name = "Physical Education and Sport"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1172),
                            IsDeleted = false,
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1174),
                            IsDeleted = false,
                            Name = "Civic Education"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1177),
                            IsDeleted = false,
                            Name = "English Language"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1178),
                            IsDeleted = false,
                            Name = "Russian Language"
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1179),
                            IsDeleted = false,
                            Name = "History"
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1181),
                            IsDeleted = false,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1182),
                            IsDeleted = false,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1183),
                            IsDeleted = false,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1185),
                            IsDeleted = false,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1186),
                            IsDeleted = false,
                            Name = "Technologies and Entrepreneurship"
                        },
                        new
                        {
                            Id = 17,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(1188),
                            IsDeleted = false,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("WeLearn.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("LessonId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            Content = "I like it!",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 213, DateTimeKind.Utc).AddTicks(2701),
                            IsDeleted = false,
                            LessonId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            Content = "Good, but can be imroved.",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 213, DateTimeKind.Utc).AddTicks(4931),
                            IsDeleted = false,
                            LessonId = 2
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            Content = "This is very nice.",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 213, DateTimeKind.Utc).AddTicks(4937),
                            IsDeleted = false,
                            LessonId = 3
                        });
                });

            modelBuilder.Entity("WeLearn.Data.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("VideoId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(7049),
                            Description = "A lecture about pronouns and when to use them.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 1,
                            Name = "Pronouns, types",
                            VideoId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8549),
                            Description = "A natural number greater than 1 that is not a product of two smaller natural numbers.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 2,
                            Name = "Prime numbers",
                            VideoId = 2
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8555),
                            Description = "About the C# language and the .NET development Platform. First steps.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 3,
                            Name = "Developing with C#",
                            VideoId = 3
                        },
                        new
                        {
                            Id = 4,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 4,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8557),
                            Description = "Data analysis.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 4,
                            Name = "Excel",
                            VideoId = 4
                        },
                        new
                        {
                            Id = 5,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 5,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8558),
                            Description = "Eastern European Countries. Their iconomic growth and political stances. Ukraine.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 5,
                            Name = "Ukraine, Eastern Europe",
                            VideoId = 5
                        },
                        new
                        {
                            Id = 6,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8560),
                            Description = "Kicking a ball on the field.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 6,
                            Name = "Football",
                            VideoId = 6
                        },
                        new
                        {
                            Id = 7,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8561),
                            Description = "A peek into Shakespere's art.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 7,
                            Name = "William Shakespere's 106 sonnet",
                            VideoId = 7
                        },
                        new
                        {
                            Id = 8,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8564),
                            Description = "A lecture about rights of the people.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 8,
                            Name = "Human rights",
                            VideoId = 8
                        },
                        new
                        {
                            Id = 9,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 9,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8565),
                            Description = "We use modals to show if we believe something is certain, possible or impossible.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 9,
                            Name = "Modal verbs",
                            VideoId = 9
                        },
                        new
                        {
                            Id = 10,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 10,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8566),
                            Description = "A lecture about the verbs of motion and when to use them.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 10,
                            Name = "Verbs of motion",
                            VideoId = 10
                        },
                        new
                        {
                            Id = 11,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 11,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8568),
                            Description = "A brief peek into our ancestors' life.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 11,
                            Name = "Peek in the past",
                            VideoId = 11
                        },
                        new
                        {
                            Id = 12,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 12,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8573),
                            Description = "A lesson about the different types of cells and their differences.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 12,
                            Name = "Cells. Prokaryotic and Eukaryotic",
                            VideoId = 12
                        },
                        new
                        {
                            Id = 13,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 13,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8575),
                            Description = "A lesson about acids, they effects on the environtment and usage cases.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 13,
                            Name = "Acids, Bases and pH",
                            VideoId = 13
                        },
                        new
                        {
                            Id = 14,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 14,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8576),
                            Description = "Genres, instruments and notation.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 14,
                            Name = "Popular music",
                            VideoId = 14
                        },
                        new
                        {
                            Id = 15,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 15,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8578),
                            Description = "Pigments, brushes, bases, matrices.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 15,
                            Name = "Painting",
                            VideoId = 15
                        },
                        new
                        {
                            Id = 16,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 16,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(8579),
                            Description = "Creating a new business, bearing most of the risks and enjoying most of the rewards.",
                            Grade = 0,
                            IsDeleted = false,
                            MaterialId = 16,
                            Name = "Entrepreneurship",
                            VideoId = 16
                        });
                });

            modelBuilder.Entity("WeLearn.Data.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(9331),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Teaching"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(839),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Teaching"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(843),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Coding"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(845),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Office Suite"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(846),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(847),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Football"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(848),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(849),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Human Rights"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(851),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Modal Verbs"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(852),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Russian Language"
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(853),
                            IsDeleted = false,
                            Link = "...",
                            Name = "History"
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(854),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(855),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(857),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(858),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Painting"
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 215, DateTimeKind.Utc).AddTicks(859),
                            IsDeleted = false,
                            Link = "...",
                            Name = "Entrepreneurship"
                        });
                });

            modelBuilder.Entity("WeLearn.Data.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<int?>("CommentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CommentId");

                    b.HasIndex("LessonId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 213, DateTimeKind.Utc).AddTicks(5948),
                            Description = "Bad language in lesson's title.",
                            IsDeleted = false,
                            LessonId = 5,
                            Subject = "The language used in title"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 213, DateTimeKind.Utc).AddTicks(7769),
                            Description = "This username is unacceptable.",
                            IsDeleted = false,
                            Subject = "Bad words in username"
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 1,
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 213, DateTimeKind.Utc).AddTicks(8183),
                            Description = "Bad language in comment.",
                            IsDeleted = false,
                            Subject = "Swearing in comment"
                        });
                });

            modelBuilder.Entity("WeLearn.Data.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(2076),
                            IsDeleted = false,
                            Link = "/uploads/videos/modal-verbs.mp4",
                            Name = "Teaching"
                        },
                        new
                        {
                            Id = 2,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4062),
                            IsDeleted = false,
                            Link = "/uploads/videos/man-teaching.mp4",
                            Name = "Teaching"
                        },
                        new
                        {
                            Id = 3,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4066),
                            IsDeleted = false,
                            Link = "/uploads/videos/coding.mp4",
                            Name = "Coding"
                        },
                        new
                        {
                            Id = 4,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4068),
                            IsDeleted = false,
                            Link = "/uploads/videos/office-suite.mp4",
                            Name = "Office Suite"
                        },
                        new
                        {
                            Id = 5,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4069),
                            IsDeleted = false,
                            Link = "/uploads/videos/eastern-europe.mp4",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 6,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4071),
                            IsDeleted = false,
                            Link = "/uploads/videos/football.mp4",
                            Name = "Football"
                        },
                        new
                        {
                            Id = 7,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4072),
                            IsDeleted = false,
                            Link = "/uploads/videos/literature.mp4",
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 8,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4073),
                            IsDeleted = false,
                            Link = "/uploads/videos/human-rights.mp4",
                            Name = "Human Rights"
                        },
                        new
                        {
                            Id = 9,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4075),
                            IsDeleted = false,
                            Link = "/uploads/videos/modal-verbs.mp4",
                            Name = "Modal Verbs"
                        },
                        new
                        {
                            Id = 10,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4076),
                            IsDeleted = false,
                            Link = "/uploads/videos/russian-language.mp4",
                            Name = "Russian Language"
                        },
                        new
                        {
                            Id = 11,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4078),
                            IsDeleted = false,
                            Link = "/uploads/videos/history.mp4",
                            Name = "History"
                        },
                        new
                        {
                            Id = 12,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4080),
                            IsDeleted = false,
                            Link = "/uploads/videos/biology.mp4",
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 13,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4082),
                            IsDeleted = false,
                            Link = "/uploads/videos/chemistry.mp4",
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 14,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4083),
                            IsDeleted = false,
                            Link = "/uploads/videos/music.mp4",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 15,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4086),
                            IsDeleted = false,
                            Link = "/uploads/videos/painting.mp4",
                            Name = "Painting"
                        },
                        new
                        {
                            Id = 16,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 4, 17, 32, 31, 214, DateTimeKind.Utc).AddTicks(4087),
                            IsDeleted = false,
                            Link = "/uploads/videos/entrepreneurship.mp4",
                            Name = "Entrepreneurship"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeLearn.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeLearn.Data.Models.Comment", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Comments")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WeLearn.Data.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("WeLearn.Data.Models.Lesson", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Lessons")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WeLearn.Data.Models.Category", "Category")
                        .WithMany("Lessons")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeLearn.Data.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeLearn.Data.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Category");

                    b.Navigation("Material");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("WeLearn.Data.Models.Report", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Reports")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WeLearn.Data.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WeLearn.Data.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ApplicationUser");

                    b.Navigation("Comment");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("WeLearn.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Lessons");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("WeLearn.Data.Models.Category", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
