// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeLearn.Data;

namespace WeLearn.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210523085828_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WeLearn.Data.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("WeLearn.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "206afdd1-c40a-48fc-80ab-244ec0453c23",
                            Email = "default@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DEFAULT@GMAIL.COM",
                            NormalizedUserName = "USERNAME",
                            PasswordHash = "AQAAAAEAACcQAAAAEAqSH6bqN29koBmFOc0puAPii4EIQqqBw1Gug6wI2j9KY5MumQq6fuUuoOvQRqg0eQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d38de91e-7d0b-47dd-880f-54b86942f2b8",
                            TwoFactorEnabled = false,
                            UserName = "Username"
                        });
                });

            modelBuilder.Entity("WeLearn.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(1251),
                            IsDeleted = false,
                            Name = "Bulgarian Language"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2179),
                            IsDeleted = false,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2183),
                            IsDeleted = false,
                            Name = "Informatics"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2184),
                            IsDeleted = false,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2186),
                            IsDeleted = false,
                            Name = "Geography"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2187),
                            IsDeleted = false,
                            Name = "Physical Education and Sport"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2189),
                            IsDeleted = false,
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2191),
                            IsDeleted = false,
                            Name = "Civic Education"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2192),
                            IsDeleted = false,
                            Name = "English Language"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2194),
                            IsDeleted = false,
                            Name = "Russian Language"
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2195),
                            IsDeleted = false,
                            Name = "History"
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2196),
                            IsDeleted = false,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2198),
                            IsDeleted = false,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2199),
                            IsDeleted = false,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2200),
                            IsDeleted = false,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2202),
                            IsDeleted = false,
                            Name = "Technologies and Entrepreneurship"
                        },
                        new
                        {
                            Id = 17,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(2203),
                            IsDeleted = false,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("WeLearn.Data.Models.ChatApp.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("WeLearn.Data.Models.ChatApp.ChatApplicationUser", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("ChatId", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ChatApplicationUsers");
                });

            modelBuilder.Entity("WeLearn.Data.Models.ChatApp.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("WeLearn.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("LessonId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            Content = "I like it!",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 743, DateTimeKind.Utc).AddTicks(4463),
                            IsDeleted = false,
                            LessonId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            Content = "The teacher is awesome.",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 743, DateTimeKind.Utc).AddTicks(6336),
                            IsDeleted = false,
                            LessonId = 2
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            Content = "This is just great.",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 743, DateTimeKind.Utc).AddTicks(6340),
                            IsDeleted = false,
                            LessonId = 3
                        });
                });

            modelBuilder.Entity("WeLearn.Data.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(8323),
                            Description = "A lecture about pronouns and when to use them.",
                            Grade = 1,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 1,
                            Name = "Pronouns, types",
                            VideoId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9626),
                            Description = "A natural number greater than 1 that is not a product of two smaller natural numbers.",
                            Grade = 2,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 2,
                            Name = "Prime numbers",
                            VideoId = 2
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9629),
                            Description = "About the C# language and the .NET development Platform. First steps.",
                            Grade = 3,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 3,
                            Name = "Developing with C#",
                            VideoId = 3
                        },
                        new
                        {
                            Id = 4,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 4,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9632),
                            Description = "Data analysis.",
                            Grade = 4,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 4,
                            Name = "Excel",
                            VideoId = 4
                        },
                        new
                        {
                            Id = 5,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 5,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9634),
                            Description = "Eastern European Countries. Their iconomic growth and political stances. Ukraine.",
                            Grade = 5,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 5,
                            Name = "Ukraine, Eastern Europe",
                            VideoId = 5
                        },
                        new
                        {
                            Id = 6,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 6,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9635),
                            Description = "Kicking a ball on the field.",
                            Grade = 6,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 6,
                            Name = "Football",
                            VideoId = 6
                        },
                        new
                        {
                            Id = 7,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 7,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9637),
                            Description = "A peek into Shakespere's art.",
                            Grade = 7,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 7,
                            Name = "William Shakespere's 106 sonnet",
                            VideoId = 7
                        },
                        new
                        {
                            Id = 8,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 8,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9639),
                            Description = "A lecture about rights of the people.",
                            Grade = 8,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 8,
                            Name = "Human rights",
                            VideoId = 8
                        },
                        new
                        {
                            Id = 9,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 9,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9642),
                            Description = "We use modals to show if we believe something is certain, possible or impossible.",
                            Grade = 9,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 9,
                            Name = "Modal verbs",
                            VideoId = 9
                        },
                        new
                        {
                            Id = 10,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 10,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9643),
                            Description = "A lecture about the verbs of motion and when to use them.",
                            Grade = 10,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 10,
                            Name = "Verbs of motion",
                            VideoId = 10
                        },
                        new
                        {
                            Id = 11,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 11,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9645),
                            Description = "A brief peek into our ancestors' life.",
                            Grade = 11,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 11,
                            Name = "Peek in the past",
                            VideoId = 11
                        },
                        new
                        {
                            Id = 12,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 12,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9648),
                            Description = "A lesson about the different types of cells and their differences.",
                            Grade = 12,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 12,
                            Name = "Cells. Prokaryotic and Eukaryotic",
                            VideoId = 12
                        },
                        new
                        {
                            Id = 13,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 13,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9652),
                            Description = "A lesson about acids, they effects on the environtment and usage cases.",
                            Grade = 0,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 13,
                            Name = "Acids, Bases and pH",
                            VideoId = 13
                        },
                        new
                        {
                            Id = 14,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 14,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9654),
                            Description = "Genres, instruments and notation.",
                            Grade = 5,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 14,
                            Name = "Popular music",
                            VideoId = 14
                        },
                        new
                        {
                            Id = 15,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 15,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9657),
                            Description = "Pigments, brushes, bases, matrices.",
                            Grade = 1,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 15,
                            Name = "Painting",
                            VideoId = 15
                        },
                        new
                        {
                            Id = 16,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CategoryId = 16,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(9660),
                            Description = "Creating a new business, bearing most of the risks and enjoying most of the rewards.",
                            Grade = 2,
                            IsApproved = true,
                            IsDeleted = false,
                            MaterialId = 16,
                            Name = "Entrepreneurship",
                            VideoId = 16
                        });
                });

            modelBuilder.Entity("WeLearn.Data.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(728),
                            IsDeleted = false,
                            LessonId = 1,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Teaching"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2054),
                            IsDeleted = false,
                            LessonId = 2,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Teaching"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2056),
                            IsDeleted = false,
                            LessonId = 3,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Coding"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2058),
                            IsDeleted = false,
                            LessonId = 4,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Office Suite"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2060),
                            IsDeleted = false,
                            LessonId = 5,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2061),
                            IsDeleted = false,
                            LessonId = 6,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Football"
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2063),
                            IsDeleted = false,
                            LessonId = 7,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2064),
                            IsDeleted = false,
                            LessonId = 8,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Human Rights"
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2065),
                            IsDeleted = false,
                            LessonId = 9,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Modal Verbs"
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2067),
                            IsDeleted = false,
                            LessonId = 10,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Russian Language"
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2068),
                            IsDeleted = false,
                            LessonId = 11,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "History"
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2069),
                            IsDeleted = false,
                            LessonId = 12,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2070),
                            IsDeleted = false,
                            LessonId = 13,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2072),
                            IsDeleted = false,
                            LessonId = 14,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2073),
                            IsDeleted = false,
                            LessonId = 15,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Painting"
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 745, DateTimeKind.Utc).AddTicks(2074),
                            IsDeleted = false,
                            LessonId = 16,
                            Link = "https://res.cloudinary.com/dgvfqp9zu/raw/upload/v1620309301/welearn-asp-net-core-app/zip-files/seed-dfd1-4ed3-a862-684cd9a35995_mdzu3z.zip",
                            Name = "Entrepreneurship"
                        });
                });

            modelBuilder.Entity("WeLearn.Data.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<int?>("CommentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CommentId");

                    b.HasIndex("LessonId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 743, DateTimeKind.Utc).AddTicks(7468),
                            Description = "Bad language in lesson's title.",
                            IsDeleted = false,
                            LessonId = 5,
                            Subject = "The language used in title"
                        },
                        new
                        {
                            Id = 3,
                            ApplicationUserId = "96f2bde2-eafb-4fe6-b5e9-fe36f009b8e6",
                            CommentId = 1,
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 743, DateTimeKind.Utc).AddTicks(9409),
                            Description = "Bad language in comment.",
                            IsDeleted = false,
                            Subject = "Unacceptable behaviour"
                        });
                });

            modelBuilder.Entity("WeLearn.Data.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(3293),
                            IsDeleted = false,
                            LessonId = 1,
                            Link = "/uploads/videos/modal-verbs.mp4",
                            Name = "Teaching"
                        },
                        new
                        {
                            Id = 2,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5022),
                            IsDeleted = false,
                            LessonId = 2,
                            Link = "/uploads/videos/man-teaching.mp4",
                            Name = "Teaching"
                        },
                        new
                        {
                            Id = 3,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5026),
                            IsDeleted = false,
                            LessonId = 3,
                            Link = "/uploads/videos/coding.mp4",
                            Name = "Coding"
                        },
                        new
                        {
                            Id = 4,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5028),
                            IsDeleted = false,
                            LessonId = 4,
                            Link = "/uploads/videos/office-suite.mp4",
                            Name = "Office Suite"
                        },
                        new
                        {
                            Id = 5,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5032),
                            IsDeleted = false,
                            LessonId = 5,
                            Link = "/uploads/videos/eastern-europe.mp4",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 6,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5033),
                            IsDeleted = false,
                            LessonId = 6,
                            Link = "/uploads/videos/football.mp4",
                            Name = "Football"
                        },
                        new
                        {
                            Id = 7,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5034),
                            IsDeleted = false,
                            LessonId = 7,
                            Link = "/uploads/videos/literature.mp4",
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 8,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5036),
                            IsDeleted = false,
                            LessonId = 8,
                            Link = "/uploads/videos/human-rights.mp4",
                            Name = "Human Rights"
                        },
                        new
                        {
                            Id = 9,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5038),
                            IsDeleted = false,
                            LessonId = 9,
                            Link = "/uploads/videos/modal-verbs.mp4",
                            Name = "Modal Verbs"
                        },
                        new
                        {
                            Id = 10,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5041),
                            IsDeleted = false,
                            LessonId = 10,
                            Link = "/uploads/videos/russian-language.mp4",
                            Name = "Russian Language"
                        },
                        new
                        {
                            Id = 11,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5104),
                            IsDeleted = false,
                            LessonId = 11,
                            Link = "/uploads/videos/history.mp4",
                            Name = "History"
                        },
                        new
                        {
                            Id = 12,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5110),
                            IsDeleted = false,
                            LessonId = 12,
                            Link = "/uploads/videos/biology.mp4",
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 13,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5111),
                            IsDeleted = false,
                            LessonId = 13,
                            Link = "/uploads/videos/chemistry.mp4",
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 14,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5113),
                            IsDeleted = false,
                            LessonId = 14,
                            Link = "/uploads/videos/music.mp4",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 15,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5115),
                            IsDeleted = false,
                            LessonId = 15,
                            Link = "/uploads/videos/painting.mp4",
                            Name = "Painting"
                        },
                        new
                        {
                            Id = 16,
                            ContentType = "video/mp4",
                            DateCreated = new DateTime(2021, 5, 23, 8, 58, 27, 744, DateTimeKind.Utc).AddTicks(5118),
                            IsDeleted = false,
                            LessonId = 16,
                            Link = "/uploads/videos/entrepreneurship.mp4",
                            Name = "Entrepreneurship"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeLearn.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeLearn.Data.Models.ChatApp.ChatApplicationUser", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Chats")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeLearn.Data.Models.ChatApp.Chat", "Chat")
                        .WithMany("ChatApplicationUsers")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("WeLearn.Data.Models.ChatApp.Message", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ChatApp.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("WeLearn.Data.Models.Comment", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Comments")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WeLearn.Data.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("WeLearn.Data.Models.Lesson", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Lessons")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WeLearn.Data.Models.Category", "Category")
                        .WithMany("Lessons")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WeLearn.Data.Models.Material", b =>
                {
                    b.HasOne("WeLearn.Data.Models.Lesson", "Lesson")
                        .WithOne("Material")
                        .HasForeignKey("WeLearn.Data.Models.Material", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("WeLearn.Data.Models.Report", b =>
                {
                    b.HasOne("WeLearn.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Reports")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WeLearn.Data.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WeLearn.Data.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ApplicationUser");

                    b.Navigation("Comment");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("WeLearn.Data.Models.Video", b =>
                {
                    b.HasOne("WeLearn.Data.Models.Lesson", "Lesson")
                        .WithOne("Video")
                        .HasForeignKey("WeLearn.Data.Models.Video", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("WeLearn.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Comments");

                    b.Navigation("Lessons");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("WeLearn.Data.Models.Category", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("WeLearn.Data.Models.ChatApp.Chat", b =>
                {
                    b.Navigation("ChatApplicationUsers");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("WeLearn.Data.Models.Lesson", b =>
                {
                    b.Navigation("Material");

                    b.Navigation("Video");
                });
#pragma warning restore 612, 618
        }
    }
}
